release 1.2.1. Switched to standard project (install, run, etc.) Standard version mechanism. 331/1/0.

diff --git a/src/main/bash/gca b/src/main/bash/gca
--- a/src/main/bash/gca
+++ b/src/main/bash/gca
@@ -1,72 +1,176 @@
 #!/bin/bash
+
+reldir=$(dirname $0)
+home_dir=${reldir}/..
+main_class=${main_class}
+memory=1024m
+
+verbose=false
+
+function debug()
+{
+    ${verbose} && echo "$@" 1>&2;
+    return 0
+}
+
+function debug-arguments
+{
+    ${verbose} && echo "${FUNCNAME[1]}($@)" 1>&2;
+    return 0
+}
+
 #
-# bash script for running a gc-analyzer
+# 'verbose' initialization
+#
+# while [ -n "$1" ]; do
+#     [ $1 = "--verbose" -o $1 = "-v" ] && verbose=true;
+#     ...
+#     shift
+# done
 #
 
-[ -f `dirname $0`/../lib/std.shlib ] && . `dirname $0`/../lib/std.shlib || \
-{ echo `dirname $0`"/../lib/std.shlib not found, gca probably not correctly installed ..." 1>&2; exit 1; }
+function fail
+{
+    echo "[error]: $@" 1>&2 && exit 1
+}
+
+function get_java_home()
+{
+    # local java_home="/usr/java/jdk64-1.7.0_45"
+    local java_home=""
+
+    if [ -n "${JAVA_HOME}" ]; then
+        debug "using JAVA_HOME from environment ${JAVA_HOME}"
+        java_home=${JAVA_HOME}
+    else
+        local name;
+        name=$(uname -n)
+        name=${name##*.}
+
+        [ "${name}" = "local" -o "${name}" = "ovidius-mbp" ] && java_home="/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home"
+    fi
+
+    echo ${java_home}
+}
+
+function get_classpath()
+{
+    debug "${FUNCNAME[0]}: home_dir=${home_dir}"
+    local first=true
+    for i in ${home_dir}/lib/*.jar; do
+        ${first} && first=false || echo -n ":"
+        echo -n ${i}
+    done
+}
+
+# may return empty string or more than one PID (in a space separated list)
+function get-gld-pids()
+{
+    pids=$(ps -ef | grep java | grep ${main_class} | awk '{print $2}')
+    echo ${pids}
+}
 
 #
-# shell wrapper debug
+# gets the pids as positional arguments. If the list is empty, attempt to detect and stop all processes
 #
+function stop()
+{
+    local pids
+    local force=false
 
-debug=false
+    while [ -n "$1" ]; do
+        if [ "$1" = "--force" ]; then
+            force=true;
+        elif [ ${1:0:2} = "--" ]; then
+            fail "unknown stop option '$1'"
+        else
+            [ "${pids}" = "" ] && pids=$1 || pids="${pids} $1"
+        fi
+        shift
+    done
 
-reldir=`dirname $0`
+    if [ "${pids}" = "" ]; then
+        pids=$(get-gld-pids) || fail "failed to get gld pids"
+    fi
 
-cygwin=false;
-os=unix
+    [ -z "${pids}" ] && { echo "no gld processes running on $(uname -n)"; exit 0; }
 
-case "`uname`" in
-    CYGWIN*)
-        cygwin=true
-        os=windows
-        sep="\;"
-    ;;
-    Linux)
-        sep=":"
-    ;;
-    Darwin)
-        sep=":"
-    ;;
-esac
+    local signal=""
+    local signal_name="SIGTERM"
+    if ${force}; then
+        signal="-9"
+        signal_name="SIGKILL"
+    fi
 
-if [ "${JAVA_HOME}" = "" ]; then
-    echo "no JAVA_HOME environment variable, set it and try again ..." 1>&2;
-    exit 1
-fi
+    for pid in ${pids}; do
+        kill ${signal} ${pid} && \
+            echo "sent ${signal_name} into gld processes (${pid})" || \
+            echo "fail to send ${signal_name} into gld processes with pid ${pid}"
+    done
+}
 
-classpath="${reldir}/../lib${sep}"
+function status()
+{
+    local pids
+    pids=$(get-gld-pids) || fail "failed to get gld pids"
+    [ -z "${pids}" ] && { echo "no gld processes running on $(uname -n)"; exit 0; }
+    echo "${pids}"
+}
 
-for i in `ls ${reldir}/../lib/*.jar`; do
-    ${cygwin} && i=`cygpath -w ${i}`
-    classpath="${classpath}${i}${sep}"
-done
-
-DEBUG_OPTS_SOCKET="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=12348"
-DEBUG_OPTS_SHMEM="-Xrunjdwp:transport=dt_shmem,server=y,suspend=y,address=run"
+debug_args=""
+output_settings=""
+background=false
+do_kill=false
 
 while [ "$1" != "" ]; do
     if [ "$1" = "--debug" ]; then
-        debug=true
-        if [ "${os}" = "windows" ]; then
-            JAVA_OPTS="${JAVA_OPTS} ${DEBUG_OPTS_SHMEM}"
-        else
-            JAVA_OPTS="${JAVA_OPTS} ${DEBUG_OPTS_SOCKET}"
-        fi
-    elif [ "$1" = "--profile" ]; then
-        PROFILING_OPTS="-agentlib:yjpagent"
-        JAVA_OPTS="${JAVA_OPTS} ${PROFILING_OPTS}"
-    elif [ "$1" != "${1/ /}" ]; then
-        # the argumment contains spaces, preserve quotes around arguments
-        ARGS="${ARGS} \"$1\""
+        debug_args="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5011"
+        verbose=true
+    elif [ "$1" = "--verbose" ]; then
+        verbose=true
+    elif [ "$1" = "--background" ]; then
+        background=true
+        args="${args} $1"
+    elif [ "$1" = "stop" ]; then
+        shift;
+        stop $@ && exit 0 || exit 1
+    elif [ "$1" = "status" ]; then
+        status && exit 0
     else
-        ARGS="${ARGS} $1"
+        args="${args} $1"
     fi
-    shift
-    continue;
+    shift;
 done
 
-debug "${JAVA_HOME}/bin/java ${JAVA_OPTS} -cp \"${classpath}\" com.novaordis.gc.cli.Main ${ARGS}"
+java_home=$(get_java_home) || fail "failed to get JAVA_HOME"
+classpath=$(get_classpath) || fail "failed to build classpath"
 
-${JAVA_HOME}/bin/java ${JAVA_OPTS} -cp "${classpath}" com.novaordis.gc.cli.Main ${ARGS}
+if ${do_kill}; then
+    #
+    # used to remotely kill gld processes stuck in receiving
+    #
+    pids=$(get-gld-pids)
+    pids=$(echo "${pids}")
+    [ -z ${pids} ] && echo "no gld processes running on $(hostname)" || { kill -9 ${pids}; echo "killed ${pids}"; }
+    exit 0
+fi
+
+java_bin="java"
+[ "${java_home}" != "" ] && java_bin="${java_home}/bin/java"
+
+command="${java_bin} -Xms${memory} -Xmx${memory} -cp ${classpath} ${debug_args} ${output_settings} ${main_class} ${args}"
+
+${verbose} && echo "${command}" 1>&2;
+
+if ${background}; then
+    nohup ${command} 1>./gld.log 2>&1 < /dev/null &
+    pid=$!
+    echo "gld launched in background (pid ${pid}), use gld stop|status to interact with it"
+    sleep 1
+else
+    ${command}
+fi
+
+
+
+
